# .github/workflows/python-ci.yml

name: Python CI for Web Sandbox Analyzer # Nama workflow, akan muncul di tab Actions GitHub

# Kapan workflow ini akan dijalankan
on:
  push: # Untuk setiap push ke branch tertentu
    branches: [ "main", "master" ] # Sesuaikan dengan nama branch utama Anda
  pull_request: # Untuk setiap pull request ke branch tertentu
    branches: [ "main", "master" ]

jobs:
  build-and-test: # Nama job (Anda bisa punya beberapa job)
    runs-on: ubuntu-latest # Tipe runner (mesin virtual) yang akan digunakan

    strategy:
      fail-fast: false # Lanjutkan tes pada versi Python lain meskipun satu versi gagal
      matrix:
        python-version: ["3.10", "3.11", "3.12"] # Daftar versi Python yang ingin diuji

    steps: # Langkah-langkah yang akan dijalankan dalam job
    - name: Checkout repository
      uses: actions/checkout@v4 # Aksi standar GitHub untuk mengambil kode dari repositori

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # Mengaktifkan caching untuk dependensi pip agar build lebih cepat

    - name: Install system dependencies for Playwright
      run: |
        # Perintah ini akan menginstal dependensi sistem yang dibutuhkan oleh browser Playwright
        # libasound2 dihapus karena menyebabkan error "no installation candidate"
        # Kita akan mengandalkan `playwright install --with-deps` untuk dependensi audio jika diperlukan.
        sudo apt-get update
        sudo apt-get install -y libnss3 libnspr4 libdbus-1-3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libgbm1 libxkbcommon0 libxrandr2 libpangocairo-1.0-0 libxshmfence1 libglib2.0-0
        # Paket yang mungkin juga berguna dan umumnya aman untuk disertakan:
        # sudo apt-get install -y --no-install-recommends libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxtst6 fonts-liberation

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright browsers
      run: |
        # Instal browser yang dibutuhkan. 
        # Menginstal hanya chromium akan lebih cepat jika itu yang utama digunakan.
        # Opsi --with-deps akan mencoba menginstal dependensi sistem browser.
        playwright install chromium --with-deps 
        # playwright install firefox --with-deps # Aktifkan jika perlu
        # playwright install webkit --with-deps # Aktifkan jika perlu
        # Atau: playwright install --with-deps # Untuk menginstal semua browser default

    - name: Run tests with pytest
      run: |
        pytest --cov=. --cov-report=xml --cov-report=html

    - name: Upload HTML coverage report as artifact
      uses: actions/upload-artifact@v4
      if: always() 
      with:
        name: coverage-report-py${{ matrix.python-version }}
        path: htmlcov/ 
      continue-on-error: true 

    # - name: Upload coverage reports to Codecov - Opsional
    #   uses: codecov/codecov-action@v4
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }} 
    #     files: ./coverage.xml 
    #     fail_ci_if_error: true 
    #   continue-on-error: true
