# .github/workflows/python-ci.yml

name: Python CI for Web Sandbox Analyzer

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    # --- PERUBAHAN DI SINI ---
    - name: Configure APT, enable all standard repositories and update
      run: |
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository main
        sudo add-apt-repository universe
        sudo add-apt-repository restricted
        sudo add-apt-repository multiverse
        sudo apt-get update -y
    # --- AKHIR PERUBAHAN ---

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright browsers and system dependencies
      run: |
        # Langkah ini sekarang akan bertanggung jawab penuh untuk menginstal dependensi sistem browser
        # setelah APT dikonfigurasi dan diupdate pada langkah sebelumnya.
        playwright install chromium --with-deps 
        # Jika Anda menggunakan browser lain, tambahkan di sini atau gunakan:
        # playwright install --with-deps

    - name: Run tests with pytest
      run: |
        pytest --cov=. --cov-report=xml --cov-report=html

    - name: Upload HTML coverage report as artifact
      uses: actions/upload-artifact@v4
      if: always() 
      with:
        name: coverage-report-py${{ matrix.python-version }}
        path: htmlcov/ 
      continue-on-error: true 

    # - name: Upload coverage reports to Codecov - Opsional
    #   uses: codecov/codecov-action@v4
    #   # ... (konfigurasi Codecov lainnya) ...
    #   continue-on-error: true
